### ISSUE TITLE
not properly working in windows

### ISSUE THREAD

**Issue by EaterOfCode** [benkaiser/node-music-player#2]
bugs found:
* When scanning it loops infinitely through all the files
* images and MP3's paths are resolved to "C:\C:\"

I may have missed some things

**Comment by benkaiser** [comment]
Some logs when hard rescanning then reloading the page (perhaps the wrong location stored in file):

```
C:\Users\benkaiser\GIT\node-music-player>node app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on port 2000
0 tracks deleted
C:\Users\benkaiser\GIT\node-music-player\node_modules\musicmetadata\lib\index.js
:66
    }, done, opts.hasOwnProperty('duration'), fsize);
                 ^
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Stream.<anonymous> (C:\Users\benkaiser\GIT\node-music-player\node_modules
\musicmetadata\lib\index.js:66:18)
    at Stream.g (events.js:199:16)
    at Stream.emit (events.js:107:17)
    at drain (C:\Users\benkaiser\GIT\node-music-player\node_modules\musicmetadat
a\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (C:\Users\benkaiser\GIT\node-music-player
\node_modules\musicmetadata\node_modules\through\index.js:45:5)
    at Stream.write (C:\Users\benkaiser\GIT\node-music-player\node_modules\music
metadata\node_modules\through\index.js:14:43)
    at Stream.stream.write (C:\Users\benkaiser\GIT\node-music-player\node_module
s\musicmetadata\node_modules\through\index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

C:\Users\benkaiser\GIT\node-music-player>l^Nn^N

C:\Users\benkaiser\GIT\node-music-player>node app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on port 2000
Error: ENOENT, stat 'C:\Users\benkaiser\GIT\node-music-player\Users\benkaiser\Mu
sic\soundcloud\smash_mouth___all_star_teddy_cream___mimmo_bootleg_.mp3'
    at Error (native)
Error: ENOENT, stat 'C:\Users\benkaiser\GIT\node-music-player\Users\benkaiser\Mu
sic\soundcloud\smash_mouth___all_star_teddy_cream___mimmo_bootleg_.mp3'
    at Error (native)
```

**Comment by benkaiser** [comment]
I fixed the above issues and now upon installing soundcloud downloading, scanning the library and most other features (except youtube unless ffmpeg is installed) should work.

If any other issues arise for windows please add them in their own issue.
