### ISSUE TITLE
index.js:108 TypeError when scanning for music

### ISSUE THREAD

**Issue by step1041** [benkaiser/node-music-player#37]
```
stephen@Stephen-Laptop:~/node-music-player$ node app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on port 2000
0 tracks deleted
/home/stephen/node-music-player/node_modules/musicmetadata/lib/index.js:108
    callback(exception, metadata)
    ^
TypeError: undefined is not a function
    at done (/home/stephen/node-music-player/node_modules/musicmetadata/lib/index.js:108:5)
    at /home/stephen/node-music-player/node_modules/musicmetadata/lib/id3v2.js:174:16
    at emitData (/home/stephen/node-music-player/node_modules/musicmetadata/node_modules/strtok2/lib/strtok.js:351:20)
    at Stream.dataListener (/home/stephen/node-music-player/node_modules/musicmetadata/node_modules/strtok2/lib/strtok.js:414:11)
    at Stream.emit (events.js:107:17)
    at Stream.<anonymous> (/home/stephen/node-music-player/node_modules/musicmetadata/lib/index.js:69:13)
    at Stream.g (events.js:199:16)
    at Stream.emit (events.js:107:17)
    at drain (/home/stephen/node-music-player/node_modules/musicmetadata/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/stephen/node-music-player/node_modules/musicmetadata/node_modules/through/index.js:45:5)
stephen@Stephen-Laptop:~/node-music-player

```

I'm not sure if I did something wrong during the install (Ubuntu Gnome 14.10 and Windows 8.1), but I'm getting this error when I do a regular scan on my library folder. It will add one song and then the application throws an error and stops. The song that does get added plays without issue, except that the art doesn't seem to get added.

**Comment by benkaiser** [comment]
He @step1041 thanks for submitting the issue.

I have identified the issue causing the failure and pushed [a fix](https://github.com/benkaiser/node-music-player/commit/27dbc45f0c16d468eea28d96a652323daa6a9152). If you update from master again and scan it should work now.
