### ISSUE TITLE
Server died when syncing libraries

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/node-music-player#46]
Crash report:

```
/home/benkaiser/HD/GIT/node-music-player/library_functions.js:596
  if(url.indexOf("://") == -1){
        ^
TypeError: Cannot read property 'indexOf' of undefined
    at Object.exports.sync_import (/home/benkaiser/HD/GIT/node-music-player/library_functions.js:596:9)
    at syncPlaylists (/home/benkaiser/HD/GIT/node-music-player/routes/index.js:461:12)
    at Socket.<anonymous> (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/compiled/index.js:250:16)
    at Socket.emit [as $emit] (events.js:107:17)
    at SocketNamespace.handlePacket (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/node_modules/socket.io/lib/manager.js:518:38)
    at WebSocket.Transport.onMessage (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/node_modules/socket.io/lib/transport.js:369:20)
    at Parser.<anonymous> (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.emit (events.js:107:17)
    at finish (/home/benkaiser/HD/GIT/node-music-player/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:295:16)
```

**Comment by benkaiser** [comment]
When local server address was set to: `127.0.0.1:2000` meaning the remote server wouldn't have a clue what the actual network address was.
